site_name: KrKr2 教程文档
site_description: KrKr2 模拟器的中文教程与项目文档站点。
site_author: colorcard
docs_dir: .mkdocs-src
site_dir: .mkdocs-site

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
